CREATE DATABASE IF NOT EXISTS tasksdb;

USE tasksdb;

DROP TABLE IF EXISTS tasks;

CREATE TABLE tasks (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    isCompleted bool NOT NULL DEFAULT false,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE taskLists (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE tasksOnLists (
    id SERIAL PRIMARY KEY,
    taskListId bigint UNSIGNED,
    taskId bigint UNSIGNED,
    assignedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (taskListId)  REFERENCES taskLists(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (taskId) REFERENCES tasks(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX tasksOnLists_unique ON tasksOnLists(taskId, taskListId);
